services:
  gateway:
    container_name: bloggy-gateway
    image: "bloggy-gateway"
    restart: always
    networks:
      - bloggy-backend
    ports:
      - 44000:6000
    build:
      context: ./src
      dockerfile: Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$ENV
    extra_hosts:
      - "host.docker.internal:host-gateway"

  identity:
    container_name: bloggy-identity
    image: "bloggy-identity"
    restart: always
    networks:
      - bloggy-backend
    build:
      context: ./src
      dockerfile: Identity/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$ENV
    extra_hosts:
      - "host.docker.internal:host-gateway"
  blog:
    container_name: bloggy-blog
    image: "bloggy-blog"
    restart: always
    networks:
      - bloggy-backend
    build:
      context: ./src
      dockerfile: Blog/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=$ENV
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  bloggy-back:
    name: bloggy-back
    driver: bridge
    ipam:
      config:
        - subnet: 172.90.0.0/16
