name: Bloggy Backend Deployment 🚀

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: 🚀 Deploy to Server
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📂 Upload files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"  # Send all files
          target: "/home/${{ secrets.SERVER_USER }}/bloggy/api"

      - name: 🔑 SSH into Server & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/bloggy/api
            echo "TesttseT"
            ls