name: Bloggy Backend Deployment 🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: 🚀 Deploy to Server - Run ${{ github.run_number }}
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: 🔑 SSH into Server for Preparation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/bloggy/api
            rm -rf ./*
            echo "Cleared the deployment directory!"

      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📂 Upload files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./*"  # Send all files
          target: "/home/${{ secrets.SERVER_USER }}/bloggy/api"

      - name: 🔑 SSH into Server & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/bloggy/api

            # Replace the environment variables
            sed -i 's/{Env}/${{ vars.ENV_NAME }}/g' deploy.sh

            ENV_NAME_LOWER=$(echo "${{ vars.ENV_NAME }}" | tr '[:upper:]' '[:lower:]')

            for dir in ./src/*/; do
              if [ -d "$dir" ]; then # Check if it's a directory
                echo "Processing directory: $dir"
                if [ -f "$dir/appsettings.json" ]; then # Check if appsettings.json exists in the directory
                  echo "Updating appsettings.json in $dir"

                  sed -i "s/{env}/$ENV_NAME_LOWER/g" "$dir/appsettings.json"

                  sed -i "s|{auth_jwt_issuer}|${{ vars.AUTH_JWT_ISSUER }}|g" "$dir/appsettings.json"
                  sed -i "s|{auth_jwt_audience}|${{ vars.AUTH_JWT_AUDIENCE }}|g" "$dir/appsettings.json"
                  sed -i "s|{auth_jwt_access_token_secret_key}|${{ secrets.AUTH_JWT_ACCESS_SECRET }}|g" "$dir/appsettings.json"
                  sed -i "s|{allowed_origins}|${{ vars.ALLOWED_ORIGINS }}|g" "$dir/appsettings.json"
                  sed -i "s|{datadog_api_key}|${{ secrets.DATADOG_API_KEY }}|g" "$dir/appsettings.json"

                else
                  echo "appsettings.json not found in $dir"
                fi
              fi
            done

            # Replace {Env} in all appsettings.json files
            #find /home/${{ secrets.SERVER_USER }}/bloggy/ -type f -name 'appsettings.json' -exec sed -i "s/{Env}/$ENV_NAME/g" {} \;
            #sed -i 's/{env}/$ENV_NAME_LOWER/g' deploy.sh

            chmod +x deploy.sh
            sudo ./deploy.sh
